name: Deploy Bun App
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to OCI A1 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd pito-buns
            git pull origin main
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"
            bun install
            bun run build
            sudo systemctl restart fambook
            
            # We delete and start to ensure PM2 picks up the 'serve' command
            # pm2 delete fambook || true
            # pm2 start server.js --name fambook --interpreter $(which bun)
            # pm2 save
