name: Deploy Bun App
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to OCI A1 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd pito-buns
            git pull origin main
            BUN_PATH=$(which bun)
            bun install
            bun run build
            
            # We delete and start to ensure PM2 picks up the 'serve' command
            pm2 delete fambook || true
            pm2 start "$BUN_PATH" --name "fambook" -- run serve
            pm2 save
